//Registro
export const MODIFICAR_INPUTS_REGISTRO = 'MODIFICAR_INPUTS_REGISTRO'



// Autorizacion
export const MODIFICAR_INPUTS_CREDENCIALES = 'MODIFICAR_INPUTS_CREDENCIALES'
export const CERRAR_SESION = 'CERRAR_SESION'
export const INICIAR_SESION = 'INICIAR_SESION'
export const ASIGNAR_USUARIO_SESION = 'ASIGNAR_USUARIO_SESION'

//Layout
export const MOSTRAR_MENSAJE = 'MOSTRAR_MENSAJE'
export const LIMPIAR_MENSAJE = 'LIMPIAR_MENSAJE'

//redprops......
export const MODIFICAR_INPUTS = 'MODIFICAR_INPUTS'
export const MOSTRAR_TIPO = 'MOSTRAR_TIPO'



